from src.action_description_factory.action_executor.admin_portal.dto import student_distribution
from src.action_description_factory.action_executor.admin_portal.dto import platform_student
from src.action_description_factory.action_executor.admin_portal.dto import platform_subject
from src.action_description_factory.action_executor.admin_portal.dto import platform_teacher
