from src.action_description_factory.action_executor.admin_portal import distribute_students_in_class_executor
from src.action_description_factory.action_executor.admin_portal import generate_calendar_executor
from src.action_description_factory.action_executor.admin_portal import global_students_list_executor
from src.action_description_factory.action_executor.admin_portal import global_subjects_list_executor
from src.action_description_factory.action_executor.admin_portal import global_teachers_list_executor
from src.action_description_factory.action_executor.admin_portal import (
    remove_calendar_weeks_for_class_until_stop_date_executor,
)
from src.action_description_factory.action_executor.admin_portal import (
    remove_calendar_weeks_for_individual_student_until_stop_date_executor,
)
from src.action_description_factory.action_executor.admin_portal import (
    remove_calendar_weeks_for_school_from_first_week_to_today_executor,
)
from src.action_description_factory.action_executor.admin_portal import remove_schedule_for_student_executor
from src.action_description_factory.action_executor.admin_portal import remove_schedule_subjects_for_student_executor
from src.action_description_factory.action_executor.admin_portal import (
    student_individual_plan_set_up_alarm_schedule_executor,
)
from src.action_description_factory.action_executor.admin_portal import student_individual_plan_set_up_schedule_executor
from src.action_description_factory.action_executor.admin_portal import student_individual_plan_set_up_subjects_executor
from src.action_description_factory.action_executor.admin_portal import teaching_load_report_executor
from src.action_description_factory.action_executor.admin_portal import breadcrumbs_navigate_home_executor
